language: ruby
rvm:
  - 2.1
  - 2.2
sudo: false
cache: bundler
before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rspec spec"
notifications:
  email:
    - peter@spreecommerce.com
  irc:
    channels:
      - "irc.freenode.org#spree"
    use_notice: true
branches:
  only:
    - master
    - 1-3-stable
    - 2-0-stable
    - 2-1-stable
    - 2-2-stable
    - 2-3-stable
