before_install: gem install bundler --pre
before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec rake spec"
notifications:
  email:
    - peter@spreecommerce.com
  irc: "irc.freenode.org#spree"
branches:
  only:
    - master
    - 1-3-stable
    - 2-0-stable
    - 2-1-stable
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0