language: ruby
rvm:
  - 1.9.3
  - 2.0.0
bundler_args: --without development production --quiet
before_script:
  - "bundle exec rake test_app"
script: "DISPLAY=:99.0 bundle exec spec"
notifications:
  email:
    - peter@spreecommerce.com
  irc:
    channels:
      - "irc.freenode.org#spree"
    use_notice: true
branches:
  only:
    - master
    - 1-3-stable
    - 2-0-stable
    - 2-1-stable
